import { StrapiImage } from './api';

// Import the image map generated by sync-images script
let imageMap: any = null;
try {
  imageMap = require('../../image-map.json');
} catch (error) {
  console.warn('Image map not found. Run npm run sync-images to generate it.');
  imageMap = { products: {}, static: {} };
}

/**
 * Get static image URL for a product image
 * Falls back to Strapi URL if static image not found
 */
export function getProductImageUrl(productSlug: string, strapiImage: StrapiImage, index = 0): string {
  // Try to get static image first
  const productImages = imageMap?.products?.[productSlug];
  if (productImages && productImages[index]) {
    return productImages[index].static;
  }

  // Fallback to Strapi URL
  const strapiUrl = process.env.NEXT_PUBLIC_STRAPI_URL || 'http://localhost:1339';
  return `${strapiUrl}${strapiImage.url}`;
}

/**
 * Get all static images for a product
 */
export function getProductImages(productSlug: string, strapiImages: StrapiImage[] = []): Array<{
  src: string;
  alt: string;
  width?: number;
  height?: number;
}> {
  const productImages = imageMap?.products?.[productSlug];

  if (productImages && productImages.length > 0) {
    // Use static images
    return productImages.map((img: any) => ({
      src: img.static,
      alt: img.alt,
      width: img.width,
      height: img.height
    }));
  }

  // Fallback to Strapi images
  const strapiUrl = process.env.NEXT_PUBLIC_STRAPI_URL || 'http://localhost:1339';
  return strapiImages.map((img) => ({
    src: `${strapiUrl}${img.url}`,
    alt: img.alternativeText || '',
    width: img.width,
    height: img.height
  }));
}

/**
 * Get static URL for static assets (logo, etc.)
 */
export function getStaticAssetUrl(strapiPath: string): string {
  // Try to get static asset first
  const staticAsset = imageMap?.static?.[strapiPath];
  if (staticAsset) {
    return staticAsset.static;
  }

  // Fallback to Strapi URL
  const strapiUrl = process.env.NEXT_PUBLIC_STRAPI_URL || 'http://localhost:1339';
  return `${strapiUrl}${strapiPath}`;
}

/**
 * Get the site logo URL
 */
export function getLogoUrl(): string {
  return getStaticAssetUrl('/uploads/tysondrawsstuff_web_logo_06_e9ebe2d054.png');
}

/**
 * Check if we're using static images (image map exists)
 */
export function isUsingStaticImages(): boolean {
  return imageMap && Object.keys(imageMap.products || {}).length > 0;
}